#!/usr/bin/env bash
# Profile-driven full deploy for a zip-Lambda + SPA project:
#   backend build → terraform apply → frontend build → S3 sync → CF invalidation.
#
# Usage: ./deploy.sh [--profile DIR] [-auto-approve]
#
# Everything deployment-specific lives in a PROFILE directory kept OUTSIDE this
# repo (gitignored), so the repo itself carries no domains, account IDs, or state:
#   DIR/app.config.json     app/branding config consumed by the build (optional)
#   DIR/terraform.tfvars    project name, region, custom domain (required)
#   DIR/backend.hcl         S3 remote-state config (optional; local state if absent)
#   DIR/terraform.tfstate   local state, used only when backend.hcl is absent
#   DIR/public/             optional static files overlaid onto the built site
#
# Defaults to ./profile.example so the repo deploys standalone as a demo.
set -euo pipefail
cd "$(dirname "$0")"
REPO="$PWD"

PROFILE="$REPO/profile.example"
APPROVE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --profile) PROFILE="$2"; shift 2 ;;
    -auto-approve|--auto-approve) APPROVE="-auto-approve"; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

PROFILE="$(cd "$PROFILE" && pwd)"
CONFIG="$PROFILE/app.config.json"
TFVARS="$PROFILE/terraform.tfvars"
TFSTATE="$PROFILE/terraform.tfstate"
BACKEND="$PROFILE/backend.hcl"

[ -f "$TFVARS" ] || { echo "Missing required profile file: $TFVARS" >&2; exit 1; }
echo "==> Profile: $PROFILE"

# A backend block can't take variables, so the remote-vs-local state choice is
# made by generating infra/backend.tf (gitignored) from the profile.
if [ -f "$BACKEND" ]; then
  STATE_MODE="remote"
  cat > infra/backend.tf <<'EOF'
# Generated by deploy.sh from the profile's backend.hcl. Do not edit or commit.
terraform {
  backend "s3" {}
}
EOF
  INIT_ARGS=(-backend-config="$BACKEND")
  STATE_ARGS=()

  # Refuse to silently begin from empty remote state while real local state still
  # exists — that would orphan every deployed resource.
  if [ -s "$TFSTATE" ] && [ "$(python3 -c 'import json,sys;print(len(json.load(open(sys.argv[1])).get("resources",[])))' "$TFSTATE" 2>/dev/null || echo 0)" -gt 0 ]; then
    echo "ERROR: $TFSTATE still holds resources, but backend.hcl selects remote state." >&2
    echo "Migrate it once, then remove the local file:" >&2
    echo "  (cd infra && terraform init -migrate-state -backend-config=\"$BACKEND\" -state=\"$TFSTATE\")" >&2
    exit 1
  fi
else
  STATE_MODE="local"
  rm -f infra/backend.tf
  INIT_ARGS=()
  STATE_ARGS=(-state="$TFSTATE")
fi
echo "==> State: $STATE_MODE"

echo "==> Building backend Lambda bundle(s)"
(cd backend && npm run build)

echo "==> Applying Terraform"
CONFIG_VAR=()
[ -f "$CONFIG" ] && CONFIG_VAR=(-var="app_config_file=$CONFIG")
(cd infra \
  && terraform init -input=false -reconfigure "${INIT_ARGS[@]}" >/dev/null \
  && terraform apply -input=false $APPROVE \
       -var-file="$TFVARS" \
       "${CONFIG_VAR[@]}" \
       "${STATE_ARGS[@]}")

tf_out() { (cd infra && terraform output "${STATE_ARGS[@]}" -raw "$1"); }

echo "==> Reading Terraform outputs"
API_URL=$(tf_out api_url)
USER_POOL_ID=$(tf_out user_pool_id)
CLIENT_ID=$(tf_out user_pool_client_id)
BUCKET=$(tf_out site_bucket)
DIST_ID=$(tf_out cloudfront_distribution_id)
SITE_URL=$(tf_out site_url)

echo "==> Building frontend"
cat > frontend/.env.production <<EOF
VITE_API_URL=$API_URL
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_CLIENT_ID=$CLIENT_ID
EOF
(cd frontend && npm run build)

# Profile-supplied favicons/images win over repo defaults.
if [ -d "$PROFILE/public" ]; then
  echo "==> Overlaying profile public/ assets"
  cp -R "$PROFILE/public/." frontend/dist/
fi

echo "==> Uploading site to s3://$BUCKET"
aws s3 sync frontend/dist "s3://$BUCKET" --delete

echo "==> Invalidating CloudFront cache"
aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*" >/dev/null

echo ""
echo "Deployed: $SITE_URL"
